# Generated by Django 5.2.17 on 2026-10-06 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_nominee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='A few capital letters, e.g. FIN', max_length=10, unique=True, verbose_name='short code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text="Validates this department's NCs and chooses the Action Owner. Can see all NCs across APIIT (read-only).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Head of Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to stop offering this for new NCs. Existing NCs keep it. (Use this instead of deleting.)', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='e.g. Finance', max_length=100, unique=True, verbose_name='department name'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to stop offering this for new NCs. Existing NCs keep it. (Use this instead of deleting.)', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(help_text='e.g. Fee collection. Keep an "Other" item.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to stop offering this for new NCs. Existing NCs keep it. (Use this instead of deleting.)', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='e.g. Internal review. Keep an "Other" item.', max_length=100, unique=True),
        ),
    ]
