# Generated by Django 5.2.17 on 2026-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clearer_list_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(help_text='e.g. Vesak Full Moon Poya Day', max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
