# Generated by Django 5.2.17 on 2026-10-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delegate',
            field=models.BooleanField(default=False, help_text='Tick for the named delegate. Role must also be NC Manager.', verbose_name='NC Manager delegate'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('nc_manager', 'NC Manager'), ('hod', 'Head of Department'), ('action_owner', 'Action Owner'), ('management', 'Management'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
