# Generated by Django 5.2.17 on 2026-10-04 14:29

import django.db.models.deletion
import ncs.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNC',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nc_id', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='NC ID')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('process_other', models.CharField(blank=True, help_text='Only if "Other" is chosen', max_length=200, verbose_name='other area / process')),
                ('description', models.TextField(help_text='What happened and which requirement was not met', verbose_name='description of the non-conformity')),
                ('date_identified', models.DateField(validators=[ncs.models.not_in_future])),
                ('source_other', models.CharField(blank=True, help_text='Only if "Other" is chosen', max_length=200, verbose_name='other source')),
                ('identified_by', models.CharField(help_text='Person in the raising department who found it', max_length=200)),
                ('logged_at', models.DateTimeField(blank=True, editable=False)),
                ('attachment', models.TextField(blank=True, max_length=100, verbose_name='supporting attachment')),
                ('severity', models.CharField(blank=True, choices=[('MINOR', 'Minor'), ('MAJOR', 'Major')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING_VALIDATION', 'Pending validation'), ('VALID', 'Valid'), ('DISPUTED', 'Disputed'), ('NOT_VALID', 'Not valid'), ('IN_PROGRESS', 'In progress'), ('PENDING_VERIFICATION', 'Pending verification'), ('CLOSED', 'Closed')], default='PENDING_VALIDATION', editable=False, max_length=25)),
                ('validation_deadline', models.DateField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, verbose_name='reason not valid')),
                ('dispute_decided_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_rationale', models.TextField(blank=True, verbose_name='dispute decision rationale')),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='target completion date')),
                ('original_target_date', models.DateField(blank=True, editable=False, null=True)),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='date action completed')),
                ('verification_outcome', models.CharField(blank=True, choices=[('EFFECTIVE', 'Effective'), ('NOT_EFFECTIVE', 'Not effective')], max_length=15)),
                ('verification_comments', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closure date')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('action_owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dispute_decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.process', verbose_name='area / process')),
                ('raising_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.department')),
                ('receiving_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.department')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.source', verbose_name='source of identification')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical NC',
                'verbose_name_plural': 'historical NCs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='NC ID')),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('process_other', models.CharField(blank=True, help_text='Only if "Other" is chosen', max_length=200, verbose_name='other area / process')),
                ('description', models.TextField(help_text='What happened and which requirement was not met', verbose_name='description of the non-conformity')),
                ('date_identified', models.DateField(validators=[ncs.models.not_in_future])),
                ('source_other', models.CharField(blank=True, help_text='Only if "Other" is chosen', max_length=200, verbose_name='other source')),
                ('identified_by', models.CharField(help_text='Person in the raising department who found it', max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, upload_to='nc_attachments/%Y/', verbose_name='supporting attachment')),
                ('severity', models.CharField(blank=True, choices=[('MINOR', 'Minor'), ('MAJOR', 'Major')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING_VALIDATION', 'Pending validation'), ('VALID', 'Valid'), ('DISPUTED', 'Disputed'), ('NOT_VALID', 'Not valid'), ('IN_PROGRESS', 'In progress'), ('PENDING_VERIFICATION', 'Pending verification'), ('CLOSED', 'Closed')], default='PENDING_VALIDATION', editable=False, max_length=25)),
                ('validation_deadline', models.DateField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, verbose_name='reason not valid')),
                ('dispute_decided_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_rationale', models.TextField(blank=True, verbose_name='dispute decision rationale')),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='target completion date')),
                ('original_target_date', models.DateField(blank=True, editable=False, null=True)),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='date action completed')),
                ('verification_outcome', models.CharField(blank=True, choices=[('EFFECTIVE', 'Effective'), ('NOT_EFFECTIVE', 'Not effective')], max_length=15)),
                ('verification_comments', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closure date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncs_owned', to=settings.AUTH_USER_MODEL)),
                ('dispute_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncs_logged', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.process', verbose_name='area / process')),
                ('raising_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncs_raised', to='core.department')),
                ('receiving_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncs_received', to='core.department')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.source', verbose_name='source of identification')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NC',
                'verbose_name_plural': 'NCs',
                'ordering': ['-year', '-sequence'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='evidence/%Y/')),
                ('link', models.URLField(blank=True, max_length=500)),
                ('description', models.CharField(max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='ncs.nc')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_notes', to='ncs.nc')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetDateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_date_changes', to='ncs.nc')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nc',
            constraint=models.UniqueConstraint(fields=('year', 'sequence'), name='unique_nc_number_per_year'),
        ),
    ]
